# Generated by Django 5.0.3 on 2024-03-13 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Knihovna',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('aboniment', models.CharField(max_length=256)),
                ('nazev_knihy', models.CharField(max_length=256)),
                ('zapujceno', models.DateField(auto_now_add=True)),
                ('vraceno', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
