# Generated by Django 5.0.3 on 2024-03-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnihovnaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knihovna',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
